InterMescyt/InterMescyt/Controllers/HeaderBanksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InterMescyt.Data;
using InterMescyt.Service;
using System.IO;

namespace InterMescyt.Controllers
{
    public class HeaderBanksController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IExportService _exportService;

        public HeaderBanksController(ApplicationDbContext context, IExportService exportService)
        {
            _context = context;
            _exportService = exportService;
        }

        // GET: HeaderBanks
        public async Task<IActionResult> Index()
        {
            return View(await _context.HeaderBanks.ToListAsync());
        }

        // GET: HeaderBanks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var headerBank = await _context.HeaderBanks.Include(h=>h.TransLineBanks)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (headerBank == null)
            {
                return NotFound();
            }

            return View(headerBank);
        }
        public IActionResult Download(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            MemoryStream stream = _exportService.ExportBankFile(id.Value);
            var content = stream.ToArray();
            stream.Flush();
            stream.Close();
            if (content == null)
                return NotFound();

            return File(content, "application/force-download", $"BankTransaction{id}.txt"); // returns a FileStreamResult
        }

        // GET: HeaderBanks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: HeaderBanks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Rnc,TransDate,InputDate")] HeaderBank headerBank)
        {
            if (ModelState.IsValid)
            {
                _context.Add(headerBank);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(headerBank);
        }

        // GET: HeaderBanks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var headerBank = await _context.HeaderBanks.FindAsync(id);
            if (headerBank == null)
            {
                return NotFound();
            }
            return View(headerBank);
        }

        // POST: HeaderBanks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Rnc,TransDate,InputDate")] HeaderBank headerBank)
        {
            if (id != headerBank.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(headerBank);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HeaderBankExists(headerBank.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(headerBank);
        }

        // GET: HeaderBanks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var headerBank = await _context.HeaderBanks
                .FirstOrDefaultAsync(m => m.Id == id);
            if (headerBank == null)
            {
                return NotFound();
            }

            return View(headerBank);
        }

        // POST: HeaderBanks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var headerBank = await _context.HeaderBanks.FindAsync(id);
            _context.HeaderBanks.Remove(headerBank);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HeaderBankExists(int id)
        {
            return _context.HeaderBanks.Any(e => e.Id == id);
        }
    }
}

InterMescyt/InterMescyt/Controllers/HeadersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InterMescyt.Data;
using InterMescyt.Service;
using System.IO;

namespace InterMescyt.Controllers
{
    public class HeadersController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly IExportService _exportService;

        public HeadersController(ApplicationDbContext context, IExportService exportService)
        {
            _context = context;
            _exportService = exportService;
        }

        // GET: Headers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Headers.ToListAsync());
        }

        // GET: Headers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var header = await _context.Headers.Include(h=>h.TransLines)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (header == null)
            {
                return NotFound();
            }

            return View(header);
        }
        public async Task<IActionResult> DetailsLine(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var header = await _context.TransLines.Include(l=>l.Header)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (header == null)
            {
                return NotFound();
            }

            return View(header);
        }

        public IActionResult Download(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            MemoryStream stream = _exportService.ExportFile(id.Value);
            var content = stream.ToArray();
            stream.Flush();
            stream.Close();
            if (content == null)
                return NotFound();

            return File(content, "application/force-download", $"Transaction{id}.txt"); // returns a FileStreamResult


        }
        public IActionResult DownloadJson(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            MemoryStream stream = _exportService.ExportJsonFile(id.Value);
            var content = stream.ToArray();
            stream.Flush();
            stream.Close();
            if (content == null)
                return NotFound();

            return File(content, "application/force-download", $"Transaction{id}.txt"); // returns a FileStreamResult


        }

        // GET: Headers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Headers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Rnc,Name,Location,TransDate,InputDate")] Header header)
        {
            if (ModelState.IsValid)
            {
                _context.Add(header);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(header);
        }

        // GET: Headers/CreateLine
        public async Task<IActionResult> CreateLine(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var header = await _context.Headers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (header == null)
            {
                return NotFound();
            }
            var ret = new TransLine { Id = 0, HeaderId = header.Id };
            return View(ret);
        }

        // POST: Headers/CreateLine
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateLine([Bind("Id,Cedula,Name,EnrollNumber,Career,AcademicIndex,Period,Title,HeaderId")] TransLine line)
        {
            line.Id = 0;
            if (ModelState.IsValid)
            {
                _context.Add(line);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Details), new { id = line.HeaderId});
            }
            return View(line);
        }

        // GET: Headers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var header = await _context.Headers.FindAsync(id);
            if (header == null)
            {
                return NotFound();
            }
            return View(header);
        }

        // POST: Headers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Rnc,Name,Location,TransDate,InputDate")] Header header)
        {
            if (id != header.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(header);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HeaderExists(header.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(header);
        }

        // GET: Headers/EditLine/5
        public async Task<IActionResult> EditLine(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var line = await _context.TransLines.FindAsync(id);
            if (line == null)
            {
                return NotFound();
            }
            return View(line);
        }

        // POST: Headers/EditLine/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditLine(int id, [Bind("Id,Cedula,Name,EnrollNumber,Career,AcademicIndex,Period,Title,HeaderId")] TransLine line)
        {
            if (id != line.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(line);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HeaderExists(line.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details), new { id = line.HeaderId});
            }
            return View(line);
        }

        // GET: Headers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var header = await _context.Headers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (header == null)
            {
                return NotFound();
            }

            return View(header);
        }

        // POST: Headers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var header = await _context.Headers.FindAsync(id);
            _context.Headers.Remove(header);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Headers/Delete/5
        public async Task<IActionResult> DeleteLine(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var line = await _context.TransLines
                .FirstOrDefaultAsync(m => m.Id == id);
            if (line == null)
            {
                return NotFound();
            }

            return View(line);
        }

        // POST: Headers/Delete/5
        [HttpPost, ActionName("DeleteLine")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteLineConfirmed(int id)
        {
            var line = await _context.TransLines.FindAsync(id);
            _context.TransLines.Remove(line);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Details), new { id = line.HeaderId });
        }

        private bool HeaderExists(int id)
        {
            return _context.Headers.Any(e => e.Id == id);
        }
    }
}

InterMescyt/InterMescyt/Views/Executions/Create.cshtml
@model InterMescyt.Data.Execution

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Execution</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Executed" /> @Html.DisplayNameFor(model => model.Executed)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InterMescyt/InterMescyt/Views/Executions/Delete.cshtml
@model InterMescyt.Data.Execution

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Execution</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Executed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Executed)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InterMescyt/InterMescyt/Views/Executions/Details.cshtml
@model InterMescyt.Data.Execution

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Execution</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Executed)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Executed)
        </dd>
    </dl>
    @if (Model.TransactionNumber != null)
    {
        <a class="btn btn-info" asp-action="Details" asp-controller="Headers" asp-route-id="@Model.TransactionNumber.Value">Go to transaction</a>
    }
    @if (Model.TransactionBankNumber != null)
    {
        <a class="btn btn-info" asp-action="Details" asp-controller="HeaderBanks" asp-route-id="@Model.TransactionBankNumber.Value">Go to transaction</a>
    }
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ExecutionLines.FirstOrDefault().Text)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExecutionLines.FirstOrDefault().ValidationMessage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExecutionLines.FirstOrDefault().Suscess)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExecutionLines.FirstOrDefault().Execution)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ExecutionLines)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Text)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValidationMessage)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Suscess)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Execution.Id)
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

InterMescyt/InterMescyt/Views/Executions/Edit.cshtml
@model InterMescyt.Data.Execution

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Execution</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Executed" /> @Html.DisplayNameFor(model => model.Executed)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InterMescyt/InterMescyt/Views/Executions/Index.cshtml
@model IEnumerable<InterMescyt.Data.Execution>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Executed)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Executed)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>